# Project Name: Aixt, https://github.com/fermarsan/aixt.git
# Author: 
# Date: 
# License: MIT
#
# Description: 
#              
port =    "port name" 
device =  "device reference"
board =   "board name"
backend = "c/arduino/nxc"

cc_linux =   "c compiler path on linux"
cc_windows = "c compiler path on windows"
cc_flags =   "c compiler flags"

path = "port path from aixt/ports"

fixed_size_arrays  = "true"
array_default_len  = 20

fixed_size_strings = "true"
string_default_len = 80

void =  "void"
bool =  "bool"

# data types 
# v_type = backend_type
i8 =    "signed char"
i16 =   "short"
int =   "long"
i64 =   "long long"
isize = "long long"
int_literal = "long"

u8 =    "unsigned char"
u16 =   "unsigned short"
u32 =   "unsigned long"
u64 =   "unsigned long long"
usize = "unsigned long long"

f32 = "float"
f64 = "double"
float_literal = "float"

rune =  "char"
string = "char []"

main_ret_type = "int"
main_params =   ""   

api_modules = [
    "pin",
    "adc",
    "pwm",
    "uart",
    "time"
]

[aliases]

