# Project Name: Aixt project, https://gitlab.com/fermarsan/aixt-project.git
# File Name: setup.toml (PC)
# Authores: Fernando Martínez Santa , Camilo Lucas , Javier Leon
# Date: 2023
# License: MIT
#
# Description: This is the setup file for the PC version of Aixt project 

port = "CY8CKIT-049"
device = "CY8C4245AXI-483"
board = "CY8CKIT-049-42XX"
backend = "native"

cc_linux =      ""
cc_windows =    "PSoC_Creator.exe"
cc_flags =      "-o"

path="Cypress/CY8CKIT-049-42XX/Config_Gral_049.cydsn"

api_modules = [
    "machine",
    "time"
]

fixed_size_arrays =  "true"
array_default_len  = 20

fixed_size_strings = "true"
string_default_len = 80

void =  ""
bool =  "bool"

i8 =    "int8"
i16 =   "int16"
int =   "int32"
i64 =   "int32"
isize = "int32"
int_literal = "int32"

u8 =    "uint8"
u16 =   "uint16"
u32 =   "uint32"
u64 =   "uint64"
usize = "uint32"

f32 = "float32"
f64 = "float64"
float_literal = "float32"

rune =  "char"
string = "char []"

mutex = "=== NOT SUPPORTED ==="
main_ret_type = "int"
main_params =   "void"   

headers =   [ 
    "project.h"
]

macros =    [
   
]

config_operator =   []

configuration = []

initialization =    [
    "CyGlobalInitEnable;",
    "uart_Start();",
    "pwm0_Start();",
    "pwm1_Start();",
    "pwm2_Start();",
    "pwm3_Start();",
    "adc_Start();",
    "amux_Start();",
    
]