# Project Name = Aixt, https =//github.com/fermarsan/aixt.git
# Author = Farith Ochoa León, Felipe Cardozo and Fernando Martínez Santa  
# Date = 2024
# License = MIT
#
# Description = This is the setup file for the ESP32-C3FH4 
#               port of Aixt project

port =    "ESP32-C3FH4"
device =  "WeAct_Studio"
board =   "ESP32-C3FH4"
backend = "arduino"

cc_linux =   "-o"
cc_windows = "C:\\Users\\dell\\Desktop\\PROGRAMAS\\Arduino IDE"
cc_flags =   "-o"

path = "WeAct_Studio/ESP32-C3FH4" 

fixed_size_arrays =  "true"
fixed_size_strings = "true"

void =  "void"
bool =  "bool"

i8 =    "int8_t"  #"char"
i16 =   "int16_t"
int =   "int32_t" #long 
i64 =   "int64_t"
isize = "int8_t"
int_literal = "int8_t"

u8 =    "uint8_t"
u16 =   "uint16_t"
u32 =   "uint32_t"
u64 =   "=== NOT SUPPORTED ==="
usize = "uint8_t"

f32 = "float"
f64 = "=== NOT SUPPORTED ==="
float_literal = "float"

rune =  "char"
string = "char []"

mutex = "=== NOT SUPPORTED ==="

main_ret_type = "int"
main_params =   "void "   

api_modules = [
    "pin",
    "adc",
    "pwm",
    "uart",
    "time"
]

[aliases]