# Project Name = Aixt, https =//github.com/fermarsan/aixt.git
# Author = Fernando Martínez Santa
# Date = 2022-2024
# License = MIT
#
# Description = This is the setup file for the Explorer16 (with PIC24)
#               port of Aixt project 
port =    "Explorer16-PIC24"
device =  "PIC24FJ128GA010"
board =   "Explorer 16"
backend = "c"

cc_linux =   ""
cc_windows = ""
cc_flags =   ""

path = "Microchip/Explorer16/PIC24"

fixed_size_arrays  = "true"
array_default_len  = 20

fixed_size_strings = "true"
string_default_len = 80

void =  "void"
bool =  "bool"

i8 =    "int8_t"
i16 =   "int16_t"
int =   "int32_t"
i64 =   "=== NOT SUPPORTED ==="
isize = "int16_t"
int_literal = "int32_t"

u8 =    "uint8_t"
u16 =   "uint16_t"
u32 =   "uint32_t"
u64 =   "=== NOT SUPPORTED ==="
usize = "uint16_t"

f32 = "float"
f64 = "=== NOT SUPPORTED ==="
float_literal = "float"

rune =  "char"
string = "char []"

main_ret_type = "int"
main_params =   "void "

api_modules = [
    "pin",
    "port",
    "adc",
    "pwm",
    "uart",
    "time"
]

[aliases]
